name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build&Push Docker image
      run: |
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        source .env && docker build . --file Dockerfile --tag ghcr.io/zelaqin/helloworld:latest --tag ghcr.io/zelaqin/helloworld:${APP_VERSION}
        docker push ghcr.io/zelaqin/helloworld:${APP_VERSION} && docker push ghcr.io/zelaqin/helloworld:latest 
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
